### PR TITLE
Upgrade vendor

### PR DESCRIPTION
**Pull request by 7ing**
- upgrade golang to 1.19
- run go get -u ./...
- fix a test case that may fail randomly

Signed-off-by: Jing Liu <jingliu@apple.com>

### CODE REVIEW

**Comment by 7ing** [comment]
@inteon The test was failed due to `Conflicting files go.mod`..... but this PR is about to change this file... 
```
# k8s.io/component-base/metrics
../../../../pkg/mod/k8s.io/component-base@v0.26.1/metrics/registry.go:35:29: undefined: atomic.Bool
note: module requires Go 1.19
```

Does the `pull-cert-manager-csi-lib-verify` script need to be updated ?

**Comment by 7ing** [comment]
Still same issue. The `pull-cert-manager-csi-lib-verify` does not use go 1.19 module.

**Comment by inteon** [comment]
> Still same issue. The `pull-cert-manager-csi-lib-verify` does not use go 1.19 module.

If you create a PR to upgrade the go version to 1.19, I'll approve it: https://github.com/jetstack/testing/blob/master/config/jobs/cert-manager/csi-lib/cert-manager-csi-lib-presubmits.yaml

**Comment by 7ing** [comment]
Thanks @inteon , good to know.
Here is the PR: https://github.com/jetstack/testing/pull/797

**Pull request merged**
