### PR TITLE
Add godoc badge, update OWNERS

### PR DESCRIPTION
**Pull request by SgtCoDFish**
OWNERS files are going to be updated across the org to use teams instead following the biweekly meeting last week. This updates the OWNERS file here to match others first, though.

Also adds a godoc badge and tweaks the README because why not!

### CODE REVIEW

**Review by irbekrm — APPROVED** [review]
Thanks @SgtCoDFish 

/lgtm

**Comment by SgtCoDFish** [comment]
/test pull-cert-manager-csi-lib-verify

again obviously not related to my changes that haven't changed code

**Review by irbekrm — APPROVED** [review]
Thanks!

/lgtm

**Comment by SgtCoDFish** [comment]
I'm going to manually add the `approved` label so this merges, since it's been LGTM'd and because it's working towards fixing the current situation with OWNERS files.

Note that my last force push was to remove Joakim (jahrlin) from the owners since he's not in the github org any more and jetbot was (understandably) complaining. I'll talk more about that in #cert-manager-dev on slack.

Thanks for the review!

**Pull request merged**
