### PR TITLE
Change CertificateRequest owner reference of pod `core/v1` -> `v1`

### LINKED ISSUE #29: CertificateRequests created by the csi driver are not garbage collected due to incorrect apiVersion
When the pods are deleted,  the corresponding CertificateRequest resources are supposed to be cleaned up by the Kubernetes garbage collector controller in the background, based on the ownerReferences. But, the background delete by gc isn't happening due to incorrect apiVersion for Pods here:
https://github.com/cert-manager/csi-lib/blob/v0.3.0/manager/manager.go#L414

Kubernetes version: v1.24.4
csi-lib version: 0.3.0

kube-controller-manager gc controller logs(anonymized) shows that the GC picks up the orphan CertificateRequest, but never deletes it, and below logs keep repeating for such an orphan object:
```
kube-controller-manager[3877594]: I0820 11:01:22.657996 3877594 garbagecollector.go:496] "Processing object" object="default/aaaaa-d5b687789-vfb57" objectUID=43e8b254-8667-4c3a-b5a7-9ae7329b75a9 kind="Pod" virtual=true
kube-controller-manager[3877594]: I0820 11:18:02.671261 3877594 garbagecollector.go:496] "Processing object" object="default/aaaaa-d5b687789-vfb57" objectUID=43e8b254-8667-4c3a-b5a7-9ae7329b75a9 kind="Pod" virtual=true
kube-controller-manager[3877594]: I0820 11:34:42.684420 3877594 garbagecollector.go:496] "Processing object" object="default/aaaaa-d5b687789-vfb57" objectUID=43e8b254-8667-4c3a-b5a7-9ae7329b75a9 kind="Pod" virtual=true
....
```

I tested by editing the ownerReferences of an orphan CertificateRequest's apiVersion from `core/v1` to `v1` and restarting the kube-controller-manager to trigger a gc graph rebuild. that orphan CR resource was cleaned up instantly in the next gc controller sync.

cc @munnerz

### PR DESCRIPTION
**Pull request by JoshVanL**
Fixes #29

### CODE REVIEW

**Review by 7ing — APPROVED** [review]

**Comment by munnerz** [comment]
Can we add an e2e test that:

1) creates a pod that uses a CSI volume
2) asserts a CR exists
3) deletes the pod
4) asserts the CR does not exist

Otherwise, lgtm :)

**Comment by JoshVanL** [comment]
@munnerz yes, sounds good to me!

The project doesn't have any e2e dep setup yet (only c-r env testing), so will do that in a separate PR containing the boilerplate. How do we feel about experimenting with nix for managing the deps? :slightly_smiling_face: 

I am of the opinion that nix flakes is growing in popularity and will become a "default" dependency management and distribution tool. csi-lib is a good project to experiment with given it has minimal end-user facing interaction and there is not much (basically only the current Dockerfile) to convert.

**Comment by JoshVanL** [comment]
@munnerz sorry, wasn’t clear and should have added a hold 😅
I meant let’s hold this PR and rebase on top of the e2e test boilerplate once that had merged.
No biggie, I’ll create an issue.

**Comment by munnerz** [comment]
> @munnerz yes, sounds good to me!
> 
> The project doesn't have any e2e dep setup yet, so will do that in a separate PR containing the boilerplate. How do we feel about experimenting with nix for managing the deps? 🙂
> 
> I am of the opinion that nix flakes is growing in popularity and will become a "default" dependency management and distribution tool. csi-lib is a good project to experiment with given it has minimal end-user facing interaction and there is not much (basically only the current Dockerfile) to convert.

I'm impartial, though given the extra complexity & knowledge required to manage/operate a nix based setup (of which as a project I don't _think_ we have much experience), I'm wary to introduce a whole new ecosystem (especially as, in this case, we already have prior art for setting up dependencies).

This _is_ a good place to experiment given the limited developer community around it, and minimal size. That said, for me at least there are a lot of unknown unknowns, which makes me wary to give a firm "let's do it 😄".

**Comment by munnerz** [comment]
> @munnerz sorry, wasn’t clear and should have added a hold 😅
> I meant let’s hold this PR and rebase on top of the e2e test boilerplate once that had merged.
> No biggie, I’ll create an issue.

😄 woops! But I think this is a valuable change for us to get merged anyway, especially as this is in the csi-lib (and we can leave it untagged if we aren't yet confident in its results) and is a really narrow change. An issue would be great 🥳

**Pull request merged**
